# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cm363rrqTviVI5H7upEAUbEtsPsUp1Y0

#**Ejercicio 1**
"""

# Entrada edad de Juan
Edad_Juan = int(input("Ingrese la edad de Juan: "))

# Proceso
Edad_Aberto = int((2/3) * Edad_Juan)
Edad_Ana = int((4/3) * Edad_Juan)
Edad_Mama= (Edad_Aberto + Edad_Juan + Edad_Ana)

# Edades
print(f"Edad de Alberto: {Edad_Aberto} años")
print(f"Edad de Juan: {Edad_Juan} años")
print(f"Edad de Ana: {Edad_Ana} años")
print(f"Edad de la mamá: {Edad_Mama} años")

"""#**Ejercicio 2**"""

suma = 0
x= 20
suma += x
y=40
x= x + y**2
suma = suma + x/y
print(f"El valor de la suma es: {suma}")

"""#**Ejercicio 3**"""

#Datos dados
Horas_trabajadas = 48
pago_hora= 5000
porcentaje_retencion= 0.125

#Incognitas
salariobruto= int(Horas_trabajadas*pago_hora)
retencion= int(salariobruto*porcentaje_retencion)
salarioneto = int(salariobruto-retencion)

print(f" El salario bruto es: {salariobruto}")
print(f" La retención de la fuente es: {retencion}")
print(f" El salario neto es: {salarioneto}")

"""#**Ejercicio 4**"""

def cubo_cuadrado(n):
  """
  Esta función entrega el cubo y cuadrado de un número n
  """
  cubo = n**3
  cuadrado = n**2
  return(f"El cuadrado de {n} es {cuadrado} y el cubo es {cubo}")

cubo_cuadrado(4)

"""#**Ejercicio 5**"""

import math as math
def area_y_longitud(r):
  """
  Esta función entrega area y la longitud de una circunferencia con radio r
  """
  Area_circulo = (math.pi*(r**2))
  Longitud_Circulo =(2*math.pi*r)
  return(f"El area de la circunferencia con radio {r} es {Area_circulo} y la longitud {Longitud_Circulo}")
area_y_longitud(3)